export const FILTER_PRODUCTS_BY_CATEGORY = "FILTER_PRODUCTS_BY_CATEGORY";
export const SORT_PRODUCTS_BY_PRICE_LOW_TO_HIGH = 'SORT_PRODUCTS_BY_PRICE_LOW_TO_HIGH';
export const SORT_PRODUCTS_BY_PRICE_HIGH_TO_LOW = 'SORT_PRODUCTS_BY_PRICE_HIGH_TO_LOW';
